version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    build: integration-tests/docker/schema-registry
    image: schema-registry-test
    ports:
      - 9090:9090
    expose:
      - 9090
